theme: jekyll-theme-hacker
title: Snel's Homepage
description: Home of thoughts and more. 
markdown: kramdown

defaults:
  - scope:
      path: "**/index.md"
    values:
      layout: "directory"
  - scope:
      path: ""
    values:
      layout: "page"