remote_theme: pages-themes/midnight@v0.2.0
title: Snel's Homepage
description: Home of thoughts and more. 
markdown: kramdown
plugins:
- jekyll-remote-theme
defaults:
  - scope:
      path: "**/index.md"
    values:
      layout: "directory"
  - scope:
      path: ""
    values:
      layout: "page"